### ISSUE TITLE
Unlike ADRIFT Runner, Frankendrift types  (Press any key to continue) after the waitkey-tag

### ISSUE THREAD

**Issue by kpeamon** [awlck/frankendrift#17]
Unlike ADRIFT Runner, Frankendrift types: (Press any key to continue) after applying the waitkey-tag. So if a game was made for the ADRIFT Runner the author might have included the message "Press any key to continue" before applying the waitkey-tag, so the player knows what to do. If somebody then plays the same game with Frankendrift,  they will get this message twice.
**Example:**
Press any key to continue
(Press any key to continue)

**Comment by awlck** [comment]
In my eyes, having two prompts like that is preferable to potentially having zero prompts (in a shoddily-coded game), but I'll put in a setting to suppress FrankenDrift's prompt if the player so chooses.
