### ISSUE TITLE
Suggest adding a Restart Hotkey

### ISSUE THREAD

**Issue by Daza99** [awlck/frankendrift#19]
In the default Runner you can press Ctrl + R to Restart the game, this is very important when testing a game and making changes in the developer and saving it, then re-run the game in runner to test the changes by pressing Ctrl+R. 

Currently in FD Ctrl+R will run Restore, which then opens a window to choose file to load. (I don't quite understand what this does, because the folder for a demo it opens does not show .taf files to open??)

I suggest that remap the Ctrl-R key as a Restart hotkey (because Ctrl+R to restart is the norm in the default Runner, those used to it wont get caught out) and the restore hotkey could be changed to Alt+R? 

I know there is a 'restart' command that can be typed but a hot-key is so much faster, especially when in the course of an hour i might restart a game 30 times when testing.

**Comment by awlck** [comment]
> Currently in FD Ctrl+R will run Restore, which then opens a window to choose file to load. (I don't quite understand what this does, because the folder for a demo it opens does not show .taf files to open??)

"Restore" is intended to load back a saved game state (a `.tas` file). I'll consider adding a shortcut for restart as well.

**Comment by Daza99** [comment]
Okay. I wouldn't have guessed that is what Restore meant. 'Load Save' would have made more sense, i am sure that will catch out a lot of users, perhaps it could be changed to 'Restore Save'? but i think Load Save would be more straight forward. Anyway that is my feedback.

**Comment by awlck** [comment]
"Restore" is the term used by the Inform library, among others, so I hoped it would be familiar enough. (The ADRIFT Runner also understands when you type `restore` as a command.) I've changed the wording to "Restore a Saved Game".

I've also added a "Restart Game" option mapped to Ctrl+Shift+R.
