### ISSUE TITLE
Please make default font bigger

### ISSUE THREAD

**Issue by kpeamon** [awlck/frankendrift#2]
I understand if it will take a while before the author or player can choose font size etc. Until then, if possible, please use a bigger default font. I find it very small on Windows and someone reported that they had to use zoom on Mac, otherwise it wasn't playable.

**Comment by awlck** [comment]
![image](https://user-images.githubusercontent.com/12954162/127391210-d15612cc-fc53-4417-a30f-c8415b5c21cc.png)

Text should be slightly larger across the board. I've also shuffled things around a bit so text styling works on Windows as well now. Might be a few days before I can pull together another release, my calendar is kinda bursting at the seams right now.
