### ISSUE TITLE
Input color can't be changed

### ISSUE THREAD

**Issue by kpeamon** [awlck/frankendrift#4]
You are probably aware that in Frankendrift **v0.1.0**, the input color is always the defaut color red, even if the author has changed it to another color. It may not seem like a big deal but the input color isn't just used for printing the input. That is because the author can choose to write text with the input color by using <<c>c>. The text color is changed back to the output color by using <</c>/c>. Toggling between text colors like that, is very effective. But as the input color is fixed in v0.1.0, you can have large chunks of text written with red when they were intended to have another color.

Here is an example that uses the "<<c>c>"-technique:
Jacaranda Jim by Campbell: https://www.adrift.co/game/1242

I also use it in several of my own games. Some messages in the standard library also uses the input color.

**Comment by awlck** [comment]
Currently, none of the default colours you pick within the Developer are respected. I'm putting this on the to-do list.

**Comment by awlck** [comment]
This will be part of the next release:

<img width="1783" alt="Bildschirmfoto 2022-01-25 um 12 59 22" src="https://user-images.githubusercontent.com/12954162/150973182-33985599-aba2-4e6b-aebc-453e79932549.png">
